version: '3.8'

services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: commander:latest
    container_name: commander
    hostname: commander
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /usr/src/app    
    environment:
      - MCP_CLIENT_DOCKER=true
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"